embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.5.2.min.js
    - public/javascripts/jquery.fancybox-1.3.4.js
    - public/javascripts/application.js
    - public/javascripts/rails.js

stylesheets:
  common:
    - public/stylesheets/jquery.fancybox-1.3.4.css
    - public/stylesheets/testopdracht.css